# TCL File Generated by Component Editor 17.1
# Sat May 12 20:01:07 EEST 2018
# DO NOT MODIFY


# 
# pulpino "pulpino" v1.0
#  2018.05.12.20:01:07
# Pulpino 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pulpino
# 
set_module_property DESCRIPTION "Pulpino "
set_module_property NAME pulpino
#set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Processors and Peripherals/Embedded Processors"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pulpino
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


set adv_dbg_if false

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL core_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file adbg_config.sv SYSTEM_VERILOG PATH include/adbg_config.sv
add_fileset_file config.sv SYSTEM_VERILOG PATH include/config.sv
add_fileset_file zeroriscy_config.sv SYSTEM_VERILOG PATH include/zeroriscy_config.sv
add_fileset_file apb_bus.sv SYSTEM_VERILOG PATH pulpino/rtl/includes/apb_bus.sv
add_fileset_file axi_bus.sv SYSTEM_VERILOG PATH pulpino/rtl/includes/axi_bus.sv
add_fileset_file debug_bus.sv SYSTEM_VERILOG PATH pulpino/rtl/includes/debug_bus.sv
add_fileset_file cluster_clock_gating.sv SYSTEM_VERILOG PATH pulpino/rtl/components/cluster_clock_gating.sv
add_fileset_file cluster_clock_inverter.sv SYSTEM_VERILOG PATH pulpino/rtl/components/cluster_clock_inverter.sv
add_fileset_file cluster_clock_mux2.sv SYSTEM_VERILOG PATH pulpino/rtl/components/cluster_clock_mux2.sv
if { $adv_dbg_if } {
    add_fileset_file adbg_axi_biu.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_axi_biu.sv
    add_fileset_file adbg_axi_module.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_axi_module.sv
    add_fileset_file adbg_crc32.v VERILOG PATH adv_dbg_if/rtl/adbg_crc32.v
    add_fileset_file adbg_lint_defines.v SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_lint_defines.v
    add_fileset_file adbg_lint_biu.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_lint_biu.sv
    add_fileset_file adbg_lint_module.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_lint_module.sv
    add_fileset_file adbg_lintonly_top.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_lintonly_top.sv
    add_fileset_file adbg_or1k_biu.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_or1k_biu.sv
    add_fileset_file adbg_or1k_module.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_or1k_module.sv
    add_fileset_file adbg_or1k_status_reg.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_or1k_status_reg.sv
    add_fileset_file adbg_tap_top.v VERILOG PATH adv_dbg_if/rtl/adbg_tap_top.v
    add_fileset_file adbg_tap_defines.v VERILOG PATH adv_dbg_if/rtl/adbg_tap_defines.v
    add_fileset_file adbg_wb_defines.v VERILOG PATH adv_dbg_if/rtl/adbg_wb_defines.v
    add_fileset_file adbg_or1k_defines.v VERILOG PATH adv_dbg_if/rtl/adbg_or1k_defines.v
    add_fileset_file adbg_defines.v VERILOG PATH adv_dbg_if/rtl/adbg_defines.v
    add_fileset_file adbg_axi_defines.v VERILOG PATH adv_dbg_if/rtl/adbg_axi_defines.v
    add_fileset_file adbg_top.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_top.sv
    add_fileset_file adbg_wb_biu.v VERILOG PATH adv_dbg_if/rtl/adbg_wb_biu.v
    add_fileset_file adbg_wb_module.v VERILOG PATH adv_dbg_if/rtl/adbg_wb_module.v
    add_fileset_file adv_dbg_if.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adv_dbg_if.sv
    add_fileset_file bytefifo.v VERILOG PATH adv_dbg_if/rtl/bytefifo.v
    add_fileset_file syncflop.v VERILOG PATH adv_dbg_if/rtl/syncflop.v
    add_fileset_file syncreg.v VERILOG PATH adv_dbg_if/rtl/syncreg.v
}
add_fileset_file zeroriscy_defines.sv SYSTEM_VERILOG PATH zero-riscy/include/zeroriscy_defines.sv
add_fileset_file zeroriscy_alu.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_alu.sv
add_fileset_file zeroriscy_compressed_decoder.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_compressed_decoder.sv
add_fileset_file zeroriscy_controller.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_controller.sv
add_fileset_file zeroriscy_core.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_core.sv
add_fileset_file zeroriscy_cs_registers.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_cs_registers.sv
add_fileset_file zeroriscy_debug_unit.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_debug_unit.sv
add_fileset_file zeroriscy_decoder.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_decoder.sv
add_fileset_file zeroriscy_ex_block.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_ex_block.sv
add_fileset_file zeroriscy_fetch_fifo.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_fetch_fifo.sv
add_fileset_file zeroriscy_id_stage.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_id_stage.sv
add_fileset_file zeroriscy_if_stage.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_if_stage.sv
add_fileset_file zeroriscy_int_controller.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_int_controller.sv
add_fileset_file zeroriscy_load_store_unit.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_load_store_unit.sv
add_fileset_file zeroriscy_multdiv_fast.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_multdiv_fast.sv
add_fileset_file zeroriscy_multdiv_slow.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_multdiv_slow.sv
add_fileset_file zeroriscy_prefetch_buffer.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_prefetch_buffer.sv
add_fileset_file zeroriscy_register_file_ff.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_register_file_ff.sv
add_fileset_file core_top.sv SYSTEM_VERILOG PATH core_top.sv TOP_LEVEL_FILE


add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
set_fileset_property SIM_VERILOG TOP_LEVEL core_top
add_fileset_file adbg_config.sv SYSTEM_VERILOG PATH include/adbg_config.sv
add_fileset_file config.sv SYSTEM_VERILOG PATH include/config.sv
add_fileset_file zeroriscy_config.sv SYSTEM_VERILOG PATH include/zeroriscy_config.sv
add_fileset_file apb_bus.sv SYSTEM_VERILOG PATH pulpino/rtl/includes/apb_bus.sv
add_fileset_file axi_bus.sv SYSTEM_VERILOG PATH pulpino/rtl/includes/axi_bus.sv
add_fileset_file debug_bus.sv SYSTEM_VERILOG PATH pulpino/rtl/includes/debug_bus.sv
add_fileset_file cluster_clock_gating.sv SYSTEM_VERILOG PATH pulpino/rtl/components/cluster_clock_gating.sv
add_fileset_file cluster_clock_inverter.sv SYSTEM_VERILOG PATH pulpino/rtl/components/cluster_clock_inverter.sv
add_fileset_file cluster_clock_mux2.sv SYSTEM_VERILOG PATH pulpino/rtl/components/cluster_clock_mux2.sv
if { $adv_dbg_if } {
    add_fileset_file adbg_axi_biu.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_axi_biu.sv
    add_fileset_file adbg_axi_module.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_axi_module.sv
    add_fileset_file adbg_crc32.v VERILOG PATH adv_dbg_if/rtl/adbg_crc32.v
    add_fileset_file adbg_lint_defines.v SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_lint_defines.v
    add_fileset_file adbg_lint_biu.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_lint_biu.sv
    add_fileset_file adbg_lint_module.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_lint_module.sv
    add_fileset_file adbg_lintonly_top.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_lintonly_top.sv
    add_fileset_file adbg_or1k_biu.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_or1k_biu.sv
    add_fileset_file adbg_or1k_module.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_or1k_module.sv
    add_fileset_file adbg_or1k_status_reg.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_or1k_status_reg.sv
    add_fileset_file adbg_tap_top.v VERILOG PATH adv_dbg_if/rtl/adbg_tap_top.v
    add_fileset_file adbg_tap_defines.v VERILOG PATH adv_dbg_if/rtl/adbg_tap_defines.v
    add_fileset_file adbg_wb_defines.v VERILOG PATH adv_dbg_if/rtl/adbg_wb_defines.v
    add_fileset_file adbg_or1k_defines.v VERILOG PATH adv_dbg_if/rtl/adbg_or1k_defines.v
    add_fileset_file adbg_defines.v VERILOG PATH adv_dbg_if/rtl/adbg_defines.v
    add_fileset_file adbg_axi_defines.v VERILOG PATH adv_dbg_if/rtl/adbg_axi_defines.v
    add_fileset_file adbg_top.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adbg_top.sv
    add_fileset_file adbg_wb_biu.v VERILOG PATH adv_dbg_if/rtl/adbg_wb_biu.v
    add_fileset_file adbg_wb_module.v VERILOG PATH adv_dbg_if/rtl/adbg_wb_module.v
    add_fileset_file adv_dbg_if.sv SYSTEM_VERILOG PATH adv_dbg_if/rtl/adv_dbg_if.sv
    add_fileset_file bytefifo.v VERILOG PATH adv_dbg_if/rtl/bytefifo.v
    add_fileset_file syncflop.v VERILOG PATH adv_dbg_if/rtl/syncflop.v
    add_fileset_file syncreg.v VERILOG PATH adv_dbg_if/rtl/syncreg.v
}
add_fileset_file zeroriscy_defines.sv SYSTEM_VERILOG PATH zero-riscy/include/zeroriscy_defines.sv
add_fileset_file zeroriscy_alu.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_alu.sv
add_fileset_file zeroriscy_compressed_decoder.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_compressed_decoder.sv
add_fileset_file zeroriscy_controller.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_controller.sv
add_fileset_file zeroriscy_core.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_core.sv
add_fileset_file zeroriscy_cs_registers.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_cs_registers.sv
add_fileset_file zeroriscy_debug_unit.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_debug_unit.sv
add_fileset_file zeroriscy_decoder.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_decoder.sv
add_fileset_file zeroriscy_ex_block.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_ex_block.sv
add_fileset_file zeroriscy_fetch_fifo.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_fetch_fifo.sv
add_fileset_file zeroriscy_id_stage.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_id_stage.sv
add_fileset_file zeroriscy_if_stage.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_if_stage.sv
add_fileset_file zeroriscy_int_controller.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_int_controller.sv
add_fileset_file zeroriscy_load_store_unit.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_load_store_unit.sv
add_fileset_file zeroriscy_multdiv_fast.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_multdiv_fast.sv
add_fileset_file zeroriscy_multdiv_slow.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_multdiv_slow.sv
add_fileset_file zeroriscy_prefetch_buffer.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_prefetch_buffer.sv
add_fileset_file zeroriscy_register_file_ff.sv SYSTEM_VERILOG PATH zero-riscy/zeroriscy_register_file_ff.sv
add_fileset_file core_top.sv SYSTEM_VERILOG PATH core_top.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AXI_ADDR_WIDTH integer 32 "AXI address width"
set_parameter_property AXI_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property AXI_ADDR_WIDTH ALLOWED_RANGES "32,64"

add_parameter AXI_DATA_WIDTH integer 32 "AXI data width"
set_parameter_property AXI_DATA_WIDTH HDL_PARAMETER true
set_parameter_property AXI_DATA_WIDTH ALLOWED_RANGES "32,64"


add_parameter AXI_ID_MASTER_WIDTH integer 10 "AXI ID master width"
set_parameter_property AXI_ID_MASTER_WIDTH HDL_PARAMETER true

add_parameter AXI_ID_SLAVE_WIDTH integer 10 "AXI ID slave width"
set_parameter_property AXI_ID_SLAVE_WIDTH HDL_PARAMETER true

add_parameter AXI_USER_WIDTH integer 0 "AXI ID user width"
set_parameter_property AXI_USER_WIDTH HDL_PARAMETER true

add_parameter USE_ZERO_RISCY boolean true "Use Zero-RISCY"
set_parameter_property USE_ZERO_RISCY HDL_PARAMETER true

add_parameter RISCY_RV32F boolean false "RISCY_RV32F"
set_parameter_property RISCY_RV32F HDL_PARAMETER true

add_parameter ZERO_RV32M boolean true "ZERO_RV32M"
set_parameter_property ZERO_RV32M HDL_PARAMETER true

add_parameter ZERO_RV32E boolean false "ZERO_RV32E"
set_parameter_property ZERO_RV32E HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clk_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point config
# 
add_interface config conduit end
set_interface_property config associatedClock clk_sink
set_interface_property config associatedReset ""
set_interface_property config ENABLED true
set_interface_property config EXPORT_OF ""
set_interface_property config PORT_NAME_MAP ""
set_interface_property config CMSIS_SVD_VARIABLES ""
set_interface_property config SVD_ADDRESS_GROUP ""

add_interface_port config testmode_i testmode_i Input 1
add_interface_port config fetch_enable_i fetch_enable_i Input 1
add_interface_port config clock_gating_i clock_gating_i Input 1
add_interface_port config boot_addr_i boot_addr_i Input 32


# 
# connection point clk_sink
# 
add_interface clk_sink clock end
set_interface_property clk_sink ENABLED true
set_interface_property clk_sink EXPORT_OF ""
set_interface_property clk_sink PORT_NAME_MAP ""
set_interface_property clk_sink CMSIS_SVD_VARIABLES ""
set_interface_property clk_sink SVD_ADDRESS_GROUP ""

add_interface_port clk_sink clk clk Input 1


# 
# connection point interrupt_receiver
# 
add_interface interrupt_receiver interrupt start
set_interface_property interrupt_receiver associatedAddressablePoint ""
set_interface_property interrupt_receiver associatedClock clk_sink
set_interface_property interrupt_receiver associatedReset reset_sink
set_interface_property interrupt_receiver irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver ENABLED true
set_interface_property interrupt_receiver EXPORT_OF ""
set_interface_property interrupt_receiver PORT_NAME_MAP ""
set_interface_property interrupt_receiver CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_receiver SVD_ADDRESS_GROUP ""

add_interface_port interrupt_receiver irq_i irq Input 32


# 
# connection point avalon_master_instr
# 
add_interface avalon_master_instr avalon start
set_interface_property avalon_master_instr addressUnits SYMBOLS
set_interface_property avalon_master_instr associatedClock clk_sink
set_interface_property avalon_master_instr associatedReset reset_sink
set_interface_property avalon_master_instr bitsPerSymbol 8
set_interface_property avalon_master_instr burstOnBurstBoundariesOnly false
set_interface_property avalon_master_instr burstcountUnits WORDS
set_interface_property avalon_master_instr doStreamReads false
set_interface_property avalon_master_instr doStreamWrites false
set_interface_property avalon_master_instr holdTime 0
set_interface_property avalon_master_instr linewrapBursts false
set_interface_property avalon_master_instr maximumPendingReadTransactions 0
set_interface_property avalon_master_instr maximumPendingWriteTransactions 0
set_interface_property avalon_master_instr readLatency 0
set_interface_property avalon_master_instr readWaitTime 1
set_interface_property avalon_master_instr setupTime 0
set_interface_property avalon_master_instr timingUnits Cycles
set_interface_property avalon_master_instr writeWaitTime 0
set_interface_property avalon_master_instr ENABLED true
set_interface_property avalon_master_instr EXPORT_OF ""
set_interface_property avalon_master_instr PORT_NAME_MAP ""
set_interface_property avalon_master_instr CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_instr SVD_ADDRESS_GROUP ""
add_interface_port avalon_master_instr instr_addr address Output 32
add_interface_port avalon_master_instr instr_rdata readdata Input 32
add_interface_port avalon_master_instr instr_read read Output 1
add_interface_port avalon_master_instr instr_rvalid readdatavalid Input 1
add_interface_port avalon_master_instr instr_busy waitrequest Input 1


# 
# connection point avalon_master_instr
# 
add_interface avalon_master_lsu avalon start
set_interface_property avalon_master_lsu addressUnits SYMBOLS
set_interface_property avalon_master_lsu associatedClock clk_sink
set_interface_property avalon_master_lsu associatedReset reset_sink
set_interface_property avalon_master_lsu bitsPerSymbol 8
set_interface_property avalon_master_lsu burstOnBurstBoundariesOnly false
set_interface_property avalon_master_lsu burstcountUnits WORDS
set_interface_property avalon_master_lsu doStreamReads false
set_interface_property avalon_master_lsu doStreamWrites false
set_interface_property avalon_master_lsu holdTime 0
set_interface_property avalon_master_lsu linewrapBursts false
set_interface_property avalon_master_lsu maximumPendingReadTransactions 0
set_interface_property avalon_master_lsu maximumPendingWriteTransactions 0
set_interface_property avalon_master_lsu readLatency 0
set_interface_property avalon_master_lsu readWaitTime 1
set_interface_property avalon_master_lsu setupTime 0
set_interface_property avalon_master_lsu timingUnits Cycles
set_interface_property avalon_master_lsu writeWaitTime 0
set_interface_property avalon_master_lsu ENABLED true
set_interface_property avalon_master_lsu EXPORT_OF ""
set_interface_property avalon_master_lsu PORT_NAME_MAP ""
set_interface_property avalon_master_lsu CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_lsu SVD_ADDRESS_GROUP ""
add_interface_port avalon_master_lsu lsu_addr address Output 32
add_interface_port avalon_master_lsu lsu_rdata readdata Input 32
add_interface_port avalon_master_lsu lsu_read read Output 1
add_interface_port avalon_master_lsu lsu_rvalid readdatavalid Input 1
add_interface_port avalon_master_lsu lsu_busy waitrequest Input 1
add_interface_port avalon_master_lsu lsu_write write Output 1
add_interface_port avalon_master_lsu lsu_be byteenable Output 4
add_interface_port avalon_master_lsu lsu_wdata writedata Output 32
add_interface_port avalon_master_lsu lsu_resp response Input 2
add_interface_port avalon_master_lsu lsu_wrespvalid writeresponsevalid Input 1


# 
# connection point avalon_slave_debug
# 
add_interface avalon_slave_debug avalon end
set_interface_property avalon_slave_debug addressUnits SYMBOLS
set_interface_property avalon_slave_debug associatedClock clk_sink
set_interface_property avalon_slave_debug associatedReset reset_sink
set_interface_property avalon_slave_debug bitsPerSymbol 8
set_interface_property avalon_slave_debug burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_debug burstcountUnits WORDS
set_interface_property avalon_slave_debug explicitAddressSpan {8192}
set_interface_property avalon_slave_debug holdTime 0
set_interface_property avalon_slave_debug linewrapBursts false
set_interface_property avalon_slave_debug maximumPendingReadTransactions 1
set_interface_property avalon_slave_debug readLatency 0
set_interface_property avalon_slave_debug readWaitTime 1
set_interface_property avalon_slave_debug setupTime 0
set_interface_property avalon_slave_debug timingUnits Cycles
set_interface_property avalon_slave_debug writeWaitTime 0
set_interface_property avalon_slave_debug ENABLED true
set_interface_property avalon_slave_debug EXPORT_OF ""
set_interface_property avalon_slave_debug PORT_NAME_MAP ""
set_interface_property avalon_slave_debug CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_debug SVD_ADDRESS_GROUP ""
add_interface_port avalon_slave_debug debug_addr address Input 15
add_interface_port avalon_slave_debug debug_rdata readdata Output 32
add_interface_port avalon_slave_debug debug_read read Input 1
add_interface_port avalon_slave_debug debug_rvalid readdatavalid Output 1
add_interface_port avalon_slave_debug debug_busy waitrequest Output 1
add_interface_port avalon_slave_debug debug_write write Input 1
add_interface_port avalon_slave_debug debug_wdata writedata Input 32


if { $adv_dbg_if } {
    # 
    # connection point avalon_master_adv_dbg_if
    # 
    add_interface avalon_master_adv_dbg_if avalon start
    set_interface_property avalon_master_adv_dbg_if addressUnits SYMBOLS
    set_interface_property avalon_master_adv_dbg_if associatedClock clk_sink
    set_interface_property avalon_master_adv_dbg_if associatedReset reset_sink
    set_interface_property avalon_master_adv_dbg_if bitsPerSymbol 8
    set_interface_property avalon_master_adv_dbg_if burstOnBurstBoundariesOnly false
    set_interface_property avalon_master_adv_dbg_if burstcountUnits WORDS
    set_interface_property avalon_master_adv_dbg_if doStreamReads false
    set_interface_property avalon_master_adv_dbg_if doStreamWrites false
    set_interface_property avalon_master_adv_dbg_if holdTime 0
    set_interface_property avalon_master_adv_dbg_if linewrapBursts false
    set_interface_property avalon_master_adv_dbg_if maximumPendingReadTransactions 0
    set_interface_property avalon_master_adv_dbg_if maximumPendingWriteTransactions 0
    set_interface_property avalon_master_adv_dbg_if readLatency 0
    set_interface_property avalon_master_adv_dbg_if readWaitTime 1
    set_interface_property avalon_master_adv_dbg_if setupTime 0
    set_interface_property avalon_master_adv_dbg_if timingUnits Cycles
    set_interface_property avalon_master_adv_dbg_if writeWaitTime 0
    set_interface_property avalon_master_adv_dbg_if ENABLED true
    set_interface_property avalon_master_adv_dbg_if EXPORT_OF ""
    set_interface_property avalon_master_adv_dbg_if PORT_NAME_MAP ""
    set_interface_property avalon_master_adv_dbg_if CMSIS_SVD_VARIABLES ""
    set_interface_property avalon_master_adv_dbg_if SVD_ADDRESS_GROUP ""

    add_interface_port avalon_master_adv_dbg_if wb_adr_o address Output 32
    add_interface_port avalon_master_adv_dbg_if wb_dat_o writedata Output 32
    add_interface_port avalon_master_adv_dbg_if wb_dat_i readdata Input 32
    add_interface_port avalon_master_adv_dbg_if wb_stb_o chipselect Output 1
    add_interface_port avalon_master_adv_dbg_if wb_sel_o byteenable Output 4
    add_interface_port avalon_master_adv_dbg_if wb_we_o write Output 1
    add_interface_port avalon_master_adv_dbg_if wb_ack_i waitrequest Input 1
    set_interface_assignment avalon_master_adv_dbg_if wb_err_i 0


    # 
    # connection point jtag
    # 
    add_interface jtag conduit end
    set_interface_property jtag associatedClock clk_sink
    set_interface_property jtag associatedReset ""
    set_interface_property jtag ENABLED true
    set_interface_property jtag EXPORT_OF ""
    set_interface_property jtag PORT_NAME_MAP ""
    set_interface_property jtag CMSIS_SVD_VARIABLES ""
    set_interface_property jtag SVD_ADDRESS_GROUP ""

    add_interface_port jtag tck_i tck_i Input 1
    add_interface_port jtag trstn_i trstn_i Input 1
    add_interface_port jtag tms_i tms_i Input 1
    add_interface_port jtag tdi_i tdi_i Input 1
    add_interface_port jtag tdo_o tdo_o Output 1
}
